-- Script Path: game:GetService("ReplicatedStorage").UpgradeDefs
-- Took 0.82s to decompile.
-- Executor: Xeno (v1.3.55)

-- https://lua.expert/
local t = {
    Upgrades = {
        {
            id = "start",
            baseId = "start",
            level = 1,
            name = "START",
            desc = "Welcome to Ball Game",
            cost = 0,
            x = 0,
            y = 0,
            effectType = "start",
            effectValue = 0,
            requires = nil
        },
        {
            id = "shooter",
            baseId = "shooter",
            level = 1,
            name = "Ball Blaster",
            desc = "Click to shoot. Shooting balls gives their base value in money and applies knockback.\n\nShooting a ball six times causes it to explode, granting max multiplier value to all balls in a 10-stud radius.",
            cost = 5000,
            x = -1,
            y = 3,
            effectType = "shooter",
            effectValue = 1,
            requires = "earnings2"
        },
        {
            id = "shooterValue1",
            baseId = "shooterValue",
            level = 1,
            name = "Blaster Value 1",
            desc = "2x Blaster Value",
            cost = 100000,
            x = -1,
            y = 4,
            effectType = "shooterValue",
            effectValue = 1,
            requires = "shooter"
        },
        {
            id = "shooterValue2",
            baseId = "shooterValue",
            level = 2,
            name = "Blaster Value 2",
            desc = "4x Blaster Value",
            cost = 10000000,
            x = -1,
            y = 5,
            effectType = "shooterValue",
            effectValue = 2,
            requires = "shooterValue1"
        },
        {
            id = "shooterValue3",
            baseId = "shooterValue",
            level = 3,
            name = "Blaster Value 3",
            desc = "8x Blaster Value",
            cost = 1000000000,
            x = -1,
            y = 6,
            effectType = "shooterValue",
            effectValue = 3,
            requires = "shooterValue2"
        },
        {
            id = "shooterValue4",
            baseId = "shooterValue",
            level = 4,
            name = "Blaster Value 4",
            desc = "16x Blaster Value",
            cost = 1000000000000,
            x = -1,
            y = 7,
            effectType = "shooterValue",
            effectValue = 4,
            requires = "shooterValue3"
        },
        {
            id = "shooterValue5",
            baseId = "shooterValue",
            level = 5,
            name = "Blaster Value 5",
            desc = "32x Blaster Value",
            cost = 1000000000000000,
            x = -1,
            y = 8,
            effectType = "shooterValue",
            effectValue = 5,
            requires = "shooterValue4"
        },
        {
            id = "shooterSpeed1",
            baseId = "shooterSpeed",
            level = 1,
            name = "Fire Rate 1",
            desc = "+10% Fire Rate",
            cost = 500,
            x = -2,
            y = 3,
            effectType = "shooterSpeed",
            effectValue = 1,
            requires = "shooter"
        },
        {
            id = "shooterSpeed2",
            baseId = "shooterSpeed",
            level = 2,
            name = "Fire Rate 2",
            desc = "+10% Fire Rate",
            cost = 20000,
            x = -3,
            y = 3,
            effectType = "shooterSpeed",
            effectValue = 2,
            requires = "shooterSpeed1"
        },
        {
            id = "shooterSpeed3",
            baseId = "shooterSpeed",
            level = 3,
            name = "Fire Rate 3",
            desc = "+10% Fire Rate",
            cost = 1000000,
            x = -4,
            y = 3,
            effectType = "shooterSpeed",
            effectValue = 3,
            requires = "shooterSpeed2"
        },
        {
            id = "shooterSpeed4",
            baseId = "shooterSpeed",
            level = 4,
            name = "Fire Rate 4",
            desc = "+10% Fire Rate",
            cost = 35000000,
            x = -5,
            y = 3,
            effectType = "shooterSpeed",
            effectValue = 4,
            requires = "shooterSpeed3"
        },
        {
            id = "shooterSpeed5",
            baseId = "shooterSpeed",
            level = 5,
            name = "Fire Rate 5",
            desc = "+10% Fire Rate",
            cost = 1000000000,
            x = -6,
            y = 3,
            effectType = "shooterSpeed",
            effectValue = 5,
            requires = "shooterSpeed4"
        },
        {
            id = "shooterSpeed6",
            baseId = "shooterSpeed",
            level = 6,
            name = "Fire Rate 6",
            desc = "+10% Fire Rate",
            cost = 25000000000,
            x = -7,
            y = 3,
            effectType = "shooterSpeed",
            effectValue = 6,
            requires = "shooterSpeed5"
        },
        {
            id = "shooterSpeed7",
            baseId = "shooterSpeed",
            level = 7,
            name = "Fire Rate 7",
            desc = "+10% Fire Rate",
            cost = 600000000000,
            x = -8,
            y = 3,
            effectType = "shooterSpeed",
            effectValue = 7,
            requires = "shooterSpeed6"
        },
        {
            id = "shooterSpeed8",
            baseId = "shooterSpeed",
            level = 8,
            name = "Fire Rate 8",
            desc = "+10% Fire Rate",
            cost = 10000000000000,
            x = -9,
            y = 3,
            effectType = "shooterSpeed",
            effectValue = 8,
            requires = "shooterSpeed7"
        },
        {
            id = "shooterSpeed9",
            baseId = "shooterSpeed",
            level = 9,
            name = "Fire Rate 9",
            desc = "+10% Fire Rate",
            cost = 150000000000000,
            x = -10,
            y = 3,
            effectType = "shooterSpeed",
            effectValue = 9,
            requires = "shooterSpeed8"
        },
        {
            id = "shooterSpeed10",
            baseId = "shooterSpeed",
            level = 10,
            name = "Fire Rate 10",
            desc = "+10% Fire Rate",
            cost = 1500000000000000,
            x = -11,
            y = 3,
            effectType = "shooterSpeed",
            effectValue = 10,
            requires = "shooterSpeed9"
        },
        {
            id = "luck1",
            baseId = "luck",
            level = 1,
            name = "Luck 1",
            desc = "x1.5 Luck Multiplier",
            cost = 100,
            x = 0,
            y = -1,
            effectType = "luck",
            effectValue = 1.5,
            requires = "start"
        },
        {
            id = "luck2",
            baseId = "luck",
            level = 2,
            name = "Luck 2",
            desc = "x1.5 Luck Multiplier",
            cost = 500,
            x = 0,
            y = -2,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck1"
        },
        {
            id = "luck3",
            baseId = "luck",
            level = 3,
            name = "Luck 3",
            desc = "x1.5 Luck Multiplier",
            cost = 3000,
            x = 0,
            y = -3,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck2"
        },
        {
            id = "luck4",
            baseId = "luck",
            level = 4,
            name = "Luck 4",
            desc = "x1.5 Luck Multiplier",
            cost = 20000,
            x = 0,
            y = -4,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck3"
        },
        {
            id = "luck5",
            baseId = "luck",
            level = 5,
            name = "Luck 5",
            desc = "x1.5 Luck Multiplier",
            cost = 150000,
            x = 0,
            y = -5,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck4"
        },
        {
            id = "luck6",
            baseId = "luck",
            level = 6,
            name = "Luck 6",
            desc = "x1.5 Luck Multiplier",
            cost = 1000000,
            x = 0,
            y = -6,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck5"
        },
        {
            id = "luck7",
            baseId = "luck",
            level = 7,
            name = "Luck 7",
            desc = "x1.5 Luck Multiplier",
            cost = 6000000,
            x = 0,
            y = -7,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck6"
        },
        {
            id = "luck8",
            baseId = "luck",
            level = 8,
            name = "Luck 8",
            desc = "x1.5 Luck Multiplier",
            cost = 35000000,
            x = 0,
            y = -8,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck7"
        },
        {
            id = "luck9",
            baseId = "luck",
            level = 9,
            name = "Luck 9",
            desc = "x1.5 Luck Multiplier",
            cost = 200000000,
            x = 0,
            y = -9,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck8"
        },
        {
            id = "luck10",
            baseId = "luck",
            level = 10,
            name = "Luck 10",
            desc = "x1.5 Luck Multiplier",
            cost = 1000000000,
            x = 0,
            y = -10,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck9"
        },
        {
            id = "luck11",
            baseId = "luck",
            level = 11,
            name = "Luck 11",
            desc = "x1.5 Luck Multiplier",
            cost = 5000000000,
            x = 0,
            y = -11,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck10"
        },
        {
            id = "luck12",
            baseId = "luck",
            level = 12,
            name = "Luck 12",
            desc = "x1.5 Luck Multiplier",
            cost = 25000000000,
            x = 0,
            y = -12,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck11"
        },
        {
            id = "luck13",
            baseId = "luck",
            level = 13,
            name = "Luck 13",
            desc = "x1.5 Luck Multiplier",
            cost = 125000000000,
            x = 0,
            y = -13,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck12"
        },
        {
            id = "luck14",
            baseId = "luck",
            level = 14,
            name = "Luck 14",
            desc = "x1.5 Luck Multiplier",
            cost = 600000000000,
            x = 0,
            y = -14,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck13"
        },
        {
            id = "luck15",
            baseId = "luck",
            level = 15,
            name = "Luck 15",
            desc = "x1.5 Luck Multiplier",
            cost = 2500000000000,
            x = 0,
            y = -15,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck14"
        },
        {
            id = "luck16",
            baseId = "luck",
            level = 16,
            name = "Luck 16",
            desc = "x1.5 Luck Multiplier",
            cost = 10000000000000,
            x = 0,
            y = -16,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck15"
        },
        {
            id = "luck17",
            baseId = "luck",
            level = 17,
            name = "Luck 17",
            desc = "x1.5 Luck Multiplier",
            cost = 40000000000000,
            x = 0,
            y = -17,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck16"
        },
        {
            id = "luck18",
            baseId = "luck",
            level = 18,
            name = "Luck 18",
            desc = "x1.5 Luck Multiplier",
            cost = 150000000000000,
            x = 0,
            y = -18,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck17"
        },
        {
            id = "luck19",
            baseId = "luck",
            level = 19,
            name = "Luck 19",
            desc = "x1.5 Luck Multiplier",
            cost = 500000000000000,
            x = 0,
            y = -19,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck18"
        },
        {
            id = "luck20",
            baseId = "luck",
            level = 20,
            name = "Luck 20",
            desc = "x1.5 Luck Multiplier",
            cost = 1500000000000000,
            x = 0,
            y = -20,
            effectType = "luck",
            effectValue = 1.5,
            requires = "luck19"
        },
        {
            id = "ultraluck1",
            baseId = "luck",
            level = 21,
            name = "Ultra Luck 1",
            desc = "+50% Luck Multiplier",
            cost = 1.5e16,
            x = 0,
            y = -21,
            effectType = "ultraluck",
            effectValue = 2,
            requires = "luck20"
        },
        {
            id = "ultraluck2",
            baseId = "luck",
            level = 22,
            name = "Ultra Luck 2",
            desc = "+50% Luck Multiplier",
            cost = 1.5e17,
            x = 0,
            y = -22,
            effectType = "ultraluck",
            effectValue = 2,
            requires = "ultraluck1"
        },
        {
            id = "ultraluck3",
            baseId = "luck",
            level = 23,
            name = "Ultra Luck 3",
            desc = "+50% Luck Multiplier",
            cost = 1.5e18,
            x = 0,
            y = -23,
            effectType = "ultraluck",
            effectValue = 2,
            requires = "ultraluck2"
        },
        {
            id = "ultraluck4",
            baseId = "luck",
            level = 24,
            name = "Ultra Luck 4",
            desc = "+50% Luck Multiplier",
            cost = 1.5e19,
            x = 0,
            y = -24,
            effectType = "ultraluck",
            effectValue = 2,
            requires = "ultraluck3"
        },
        {
            id = "ultraluck5",
            baseId = "luck",
            level = 25,
            name = "Ultra Luck 5",
            desc = "+50% Luck Multiplier",
            cost = 1.5e20,
            x = 0,
            y = -25,
            effectType = "ultraluck",
            effectValue = 2,
            requires = "ultraluck4"
        },
        {
            id = "ultraluck6",
            baseId = "luck",
            level = 26,
            name = "Ultra Luck 6",
            desc = "+50% Luck Multiplier",
            cost = 1.5e21,
            x = 0,
            y = -26,
            effectType = "ultraluck",
            effectValue = 2,
            requires = "ultraluck5"
        },
        {
            id = "ultraluck7",
            baseId = "luck",
            level = 27,
            name = "Ultra Luck 7",
            desc = "+50% Luck Multiplier",
            cost = 1.5e22,
            x = 0,
            y = -27,
            effectType = "ultraluck",
            effectValue = 2,
            requires = "ultraluck6"
        },
        {
            id = "ultraluck8",
            baseId = "luck",
            level = 28,
            name = "Ultra Luck 8",
            desc = "+50% Luck Multiplier",
            cost = 1.5e23,
            x = 0,
            y = -28,
            effectType = "ultraluck",
            effectValue = 2,
            requires = "ultraluck7"
        },
        {
            id = "ultraluck9",
            baseId = "luck",
            level = 29,
            name = "Ultra Luck 9",
            desc = "+50% Luck Multiplier",
            cost = 1.5e24,
            x = 0,
            y = -29,
            effectType = "ultraluck",
            effectValue = 2,
            requires = "ultraluck8"
        },
        {
            id = "ultraluck10",
            baseId = "luck",
            level = 30,
            name = "Ultra Luck 10",
            desc = "+50% Luck Multiplier",
            cost = 1.5e25,
            x = 0,
            y = -30,
            effectType = "ultraluck",
            effectValue = 2,
            requires = "ultraluck9"
        },
        {
            id = "ultraluck11",
            baseId = "luck",
            level = 31,
            name = "Ultra Luck 11",
            desc = "+50% Luck Multiplier",
            cost = 1.5e26,
            x = 0,
            y = -31,
            effectType = "ultraluck",
            effectValue = 2,
            requires = "ultraluck10"
        },
        {
            id = "ultraluck12",
            baseId = "luck",
            level = 32,
            name = "Ultra Luck 12",
            desc = "+50% Luck Multiplier",
            cost = 1.5e27,
            x = 0,
            y = -32,
            effectType = "ultraluck",
            effectValue = 2,
            requires = "ultraluck11"
        },
        {
            id = "ultraluck13",
            baseId = "luck",
            level = 33,
            name = "Ultra Luck 13",
            desc = "+50% Luck Multiplier",
            cost = 1.5e28,
            x = 0,
            y = -33,
            effectType = "ultraluck",
            effectValue = 2,
            requires = "ultraluck12"
        },
        {
            id = "ultraluck14",
            baseId = "luck",
            level = 34,
            name = "Ultra Luck 14",
            desc = "+50% Luck Multiplier",
            cost = 1.5e29,
            x = 0,
            y = -34,
            effectType = "ultraluck",
            effectValue = 2,
            requires = "ultraluck13"
        },
        {
            id = "ultraluck15",
            baseId = "luck",
            level = 35,
            name = "Ultra Luck 15",
            desc = "+50% Luck Multiplier",
            cost = 1.5e30,
            x = 0,
            y = -35,
            effectType = "ultraluck",
            effectValue = 2,
            requires = "ultraluck14"
        },
        {
            id = "unlockShiny",
            baseId = "unlockShiny",
            level = 1,
            name = "Shiny Balls",
            desc = "1% chance to roll shiny balls",
            cost = 500000,
            x = -1,
            y = -6,
            effectType = "unlockShiny",
            effectValue = 1,
            requires = "luck5"
        },
        {
            id = "unlockAura",
            baseId = "unlockAura",
            level = 1,
            name = "Aura Balls",
            desc = ".1% chance to roll aura balls",
            cost = 5000000,
            x = -2,
            y = -7,
            effectType = "unlockAura",
            effectValue = 1,
            requires = "unlockShiny"
        },
        {
            id = "unlockCorrupted",
            baseId = "unlockCorrupted",
            level = 1,
            name = "Corrupted Balls",
            desc = ".01% chance to roll corrupted balls",
            cost = 5000000000,
            x = -3,
            y = -8,
            effectType = "unlockCorrupted",
            effectValue = 1,
            requires = "unlockAura"
        },
        {
            id = "unlockAscended",
            baseId = "unlockAscended",
            level = 1,
            name = "Ascended Balls",
            desc = ".001% chance to roll ascended balls",
            cost = 5000000000000,
            x = -4,
            y = -9,
            effectType = "unlockAscended",
            effectValue = 1,
            requires = "unlockCorrupted"
        },
        {
            id = "jackpot1",
            baseId = "jackpot",
            level = 1,
            name = "Jackpot Chance I",
            desc = "+0.02% Jackpot Roll Chance",
            cost = 2500000000,
            x = 1,
            y = -11,
            effectType = "jackpot",
            effectValue = 0.0002,
            requires = "luck10"
        },
        {
            id = "jackpot2",
            baseId = "jackpot",
            level = 2,
            name = "Jackpot Chance II",
            desc = "+0.03% Jackpot Roll Chance",
            cost = 5000000000,
            x = 2,
            y = -12,
            effectType = "jackpot",
            effectValue = 0.0003,
            requires = "jackpot1"
        },
        {
            id = "jackpot3",
            baseId = "jackpot",
            level = 3,
            name = "Jackpot Chance III",
            desc = "+0.05% Jackpot Roll Chance",
            cost = 10000000000,
            x = 3,
            y = -13,
            effectType = "jackpot",
            effectValue = 0.0005,
            requires = "jackpot2"
        },
        {
            id = "jackpotBoost",
            baseId = "jackpotBoost",
            level = 1,
            name = "Jackpot Boost",
            desc = "Jackpot uses 2000x Luck",
            cost = 1000000000000,
            x = 4,
            y = -14,
            effectType = "jackpotBoost",
            effectValue = 1,
            requires = "jackpot3"
        },
        {
            id = "autoDrop",
            baseId = "autoDrop",
            level = 1,
            name = "Auto Drop",
            desc = "Automatically drop balls",
            cost = 50,
            x = 1,
            y = -1,
            effectType = "autoDrop",
            effectValue = 1,
            requires = "start"
        },
        {
            id = "dropSpeed1",
            baseId = "dropSpeed",
            level = 1,
            name = "Drop Speed 1",
            desc = "+10% Drop Speed",
            cost = 100,
            x = 2,
            y = -2,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "autoDrop"
        },
        {
            id = "dropSpeed2",
            baseId = "dropSpeed",
            level = 2,
            name = "Drop Speed 2",
            desc = "+10% Drop Speed",
            cost = 500,
            x = 3,
            y = -3,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed1"
        },
        {
            id = "dropSpeed3",
            baseId = "dropSpeed",
            level = 3,
            name = "Drop Speed 3",
            desc = "+10% Drop Speed",
            cost = 3000,
            x = 4,
            y = -4,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed2"
        },
        {
            id = "dropSpeed4",
            baseId = "dropSpeed",
            level = 4,
            name = "Drop Speed 4",
            desc = "+10% Drop Speed",
            cost = 20000,
            x = 5,
            y = -5,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed3"
        },
        {
            id = "dropSpeed5",
            baseId = "dropSpeed",
            level = 5,
            name = "Drop Speed 5",
            desc = "+10% Drop Speed",
            cost = 150000,
            x = 6,
            y = -6,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed4"
        },
        {
            id = "dropSpeed6",
            baseId = "dropSpeed",
            level = 6,
            name = "Drop Speed 6",
            desc = "+10% Drop Speed",
            cost = 1000000,
            x = 7,
            y = -7,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed5"
        },
        {
            id = "dropSpeed7",
            baseId = "dropSpeed",
            level = 7,
            name = "Drop Speed 7",
            desc = "+10% Drop Speed",
            cost = 6000000,
            x = 8,
            y = -8,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed6"
        },
        {
            id = "dropSpeed8",
            baseId = "dropSpeed",
            level = 8,
            name = "Drop Speed 8",
            desc = "+10% Drop Speed",
            cost = 35000000,
            x = 9,
            y = -9,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed7"
        },
        {
            id = "dropSpeed9",
            baseId = "dropSpeed",
            level = 9,
            name = "Drop Speed 9",
            desc = "+10% Drop Speed",
            cost = 200000000,
            x = 10,
            y = -10,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed8"
        },
        {
            id = "dropSpeed10",
            baseId = "dropSpeed",
            level = 10,
            name = "Drop Speed 10",
            desc = "+10% Drop Speed",
            cost = 1000000000,
            x = 11,
            y = -11,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed9"
        },
        {
            id = "dropSpeed11",
            baseId = "dropSpeed",
            level = 11,
            name = "Drop Speed 11",
            desc = "+10% Drop Speed",
            cost = 5000000000,
            x = 12,
            y = -12,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed10"
        },
        {
            id = "dropSpeed12",
            baseId = "dropSpeed",
            level = 12,
            name = "Drop Speed 12",
            desc = "+10% Drop Speed",
            cost = 25000000000,
            x = 13,
            y = -13,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed11"
        },
        {
            id = "dropSpeed13",
            baseId = "dropSpeed",
            level = 13,
            name = "Drop Speed 13",
            desc = "+10% Drop Speed",
            cost = 125000000000,
            x = 14,
            y = -14,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed12"
        },
        {
            id = "dropSpeed14",
            baseId = "dropSpeed",
            level = 14,
            name = "Drop Speed 14",
            desc = "+10% Drop Speed",
            cost = 600000000000,
            x = 15,
            y = -15,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed13"
        },
        {
            id = "dropSpeed15",
            baseId = "dropSpeed",
            level = 15,
            name = "Drop Speed 15",
            desc = "+10% Drop Speed",
            cost = 2500000000000,
            x = 16,
            y = -16,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed14"
        },
        {
            id = "dropSpeed16",
            baseId = "dropSpeed",
            level = 16,
            name = "Drop Speed 16",
            desc = "+10% Drop Speed",
            cost = 10000000000000,
            x = 17,
            y = -17,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed15"
        },
        {
            id = "dropSpeed17",
            baseId = "dropSpeed",
            level = 17,
            name = "Drop Speed 17",
            desc = "+10% Drop Speed",
            cost = 40000000000000,
            x = 18,
            y = -18,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed16"
        },
        {
            id = "dropSpeed18",
            baseId = "dropSpeed",
            level = 18,
            name = "Drop Speed 18",
            desc = "+10% Drop Speed",
            cost = 150000000000000,
            x = 19,
            y = -19,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed17"
        },
        {
            id = "dropSpeed19",
            baseId = "dropSpeed",
            level = 19,
            name = "Drop Speed 19",
            desc = "+10% Drop Speed",
            cost = 500000000000000,
            x = 20,
            y = -20,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed18"
        },
        {
            id = "dropSpeed20",
            baseId = "dropSpeed",
            level = 20,
            name = "Drop Speed 20",
            desc = "+10% Drop Speed",
            cost = 1500000000000000,
            x = 21,
            y = -21,
            effectType = "dropSpeed",
            effectValue = 0.1,
            requires = "dropSpeed19"
        },
        {
            id = "offline",
            baseId = "offline",
            level = 1,
            name = "Offline Rewards",
            desc = "Earn rewards while away (6h cap)",
            cost = 500,
            x = 1,
            y = 0,
            effectType = "offline",
            effectValue = 1,
            requires = "start"
        },
        {
            id = "offlineDur1",
            baseId = "offlineDur",
            level = 1,
            name = "Offline Duration I",
            desc = "Offline cap +3h",
            cost = 5000,
            x = 2,
            y = -0.5,
            effectType = "offlineDuration",
            effectValue = 3,
            requires = "offline"
        },
        {
            id = "offlineDur2",
            baseId = "offlineDur",
            level = 2,
            name = "Offline Duration II",
            desc = "Offline cap +3h",
            cost = 50000,
            x = 3,
            y = -1,
            effectType = "offlineDuration",
            effectValue = 3,
            requires = "offlineDur1"
        },
        {
            id = "offlineBoost1",
            baseId = "offlineBoost",
            level = 1,
            name = "Offline Boost I",
            desc = "+25% Offline Earnings",
            cost = 2500,
            x = 2,
            y = 0.5,
            effectType = "offlineBoost",
            effectValue = 0.25,
            requires = "offline"
        },
        {
            id = "offlineBoost2",
            baseId = "offlineBoost",
            level = 2,
            name = "Offline Boost II",
            desc = "+25% Offline Earnings",
            cost = 25000,
            x = 3,
            y = 1,
            effectType = "offlineBoost",
            effectValue = 0.25,
            requires = "offlineBoost1"
        },
        {
            id = "autoRoll",
            baseId = "autoRoll",
            level = 1,
            name = "Auto Roll",
            desc = "Automatically roll balls",
            cost = 25,
            x = 1,
            y = 1,
            effectType = "autoRoll",
            effectValue = 1,
            requires = "start"
        },
        {
            id = "rollSpeed1",
            baseId = "rollSpeed",
            level = 1,
            name = "Roll Speed 1",
            desc = "+10% Roll Speed",
            cost = 100,
            x = 2,
            y = 2,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "autoRoll"
        },
        {
            id = "rollSpeed2",
            baseId = "rollSpeed",
            level = 2,
            name = "Roll Speed 2",
            desc = "+10% Roll Speed",
            cost = 500,
            x = 3,
            y = 3,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed1"
        },
        {
            id = "rollSpeed3",
            baseId = "rollSpeed",
            level = 3,
            name = "Roll Speed 3",
            desc = "+10% Roll Speed",
            cost = 3000,
            x = 4,
            y = 4,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed2"
        },
        {
            id = "rollSpeed4",
            baseId = "rollSpeed",
            level = 4,
            name = "Roll Speed 4",
            desc = "+10% Roll Speed",
            cost = 20000,
            x = 5,
            y = 5,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed3"
        },
        {
            id = "rollSpeed5",
            baseId = "rollSpeed",
            level = 5,
            name = "Roll Speed 5",
            desc = "+10% Roll Speed",
            cost = 150000,
            x = 6,
            y = 6,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed4"
        },
        {
            id = "rollSpeed6",
            baseId = "rollSpeed",
            level = 6,
            name = "Roll Speed 6",
            desc = "+10% Roll Speed",
            cost = 1000000,
            x = 7,
            y = 7,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed5"
        },
        {
            id = "rollSpeed7",
            baseId = "rollSpeed",
            level = 7,
            name = "Roll Speed 7",
            desc = "+10% Roll Speed",
            cost = 6000000,
            x = 8,
            y = 8,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed6"
        },
        {
            id = "rollSpeed8",
            baseId = "rollSpeed",
            level = 8,
            name = "Roll Speed 8",
            desc = "+10% Roll Speed",
            cost = 35000000,
            x = 9,
            y = 9,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed7"
        },
        {
            id = "rollSpeed9",
            baseId = "rollSpeed",
            level = 9,
            name = "Roll Speed 9",
            desc = "+10% Roll Speed",
            cost = 200000000,
            x = 10,
            y = 10,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed8"
        },
        {
            id = "rollSpeed10",
            baseId = "rollSpeed",
            level = 10,
            name = "Roll Speed 10",
            desc = "+10% Roll Speed",
            cost = 1000000000,
            x = 11,
            y = 11,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed9"
        },
        {
            id = "rollSpeed11",
            baseId = "rollSpeed",
            level = 11,
            name = "Roll Speed 11",
            desc = "+10% Roll Speed",
            cost = 5000000000,
            x = 12,
            y = 12,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed10"
        },
        {
            id = "rollSpeed12",
            baseId = "rollSpeed",
            level = 12,
            name = "Roll Speed 12",
            desc = "+10% Roll Speed",
            cost = 25000000000,
            x = 13,
            y = 13,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed11"
        },
        {
            id = "rollSpeed13",
            baseId = "rollSpeed",
            level = 13,
            name = "Roll Speed 13",
            desc = "+10% Roll Speed",
            cost = 125000000000,
            x = 14,
            y = 14,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed12"
        },
        {
            id = "rollSpeed14",
            baseId = "rollSpeed",
            level = 14,
            name = "Roll Speed 14",
            desc = "+10% Roll Speed",
            cost = 600000000000,
            x = 15,
            y = 15,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed13"
        },
        {
            id = "rollSpeed15",
            baseId = "rollSpeed",
            level = 15,
            name = "Roll Speed 15",
            desc = "+10% Roll Speed",
            cost = 2500000000000,
            x = 16,
            y = 16,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed14"
        },
        {
            id = "rollSpeed16",
            baseId = "rollSpeed",
            level = 16,
            name = "Roll Speed 16",
            desc = "+10% Roll Speed",
            cost = 10000000000000,
            x = 17,
            y = 17,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed15"
        },
        {
            id = "rollSpeed17",
            baseId = "rollSpeed",
            level = 17,
            name = "Roll Speed 17",
            desc = "+10% Roll Speed",
            cost = 40000000000000,
            x = 18,
            y = 18,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed16"
        },
        {
            id = "rollSpeed18",
            baseId = "rollSpeed",
            level = 18,
            name = "Roll Speed 18",
            desc = "+10% Roll Speed",
            cost = 150000000000000,
            x = 19,
            y = 19,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed17"
        },
        {
            id = "rollSpeed19",
            baseId = "rollSpeed",
            level = 19,
            name = "Roll Speed 19",
            desc = "+10% Roll Speed",
            cost = 500000000000000,
            x = 20,
            y = 20,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed18"
        },
        {
            id = "rollSpeed20",
            baseId = "rollSpeed",
            level = 20,
            name = "Roll Speed 20",
            desc = "+10% Roll Speed",
            cost = 1500000000000000,
            x = 21,
            y = 21,
            effectType = "rollSpeed",
            effectValue = 0.1,
            requires = "rollSpeed19"
        },
        {
            id = "goldenRoll",
            baseId = "goldenRoll",
            level = 1,
            name = "Golden Roll",
            desc = "Every 10 rolls grants +5x Luck!",
            cost = 10000,
            x = 5,
            y = 3,
            effectType = "goldenRoll",
            effectValue = 1,
            requires = "rollSpeed3"
        },
        {
            id = "diamondRoll",
            baseId = "diamondRoll",
            level = 1,
            name = "Diamond Roll",
            desc = "Every 100 rolls grants +50x Luck!",
            cost = 1000000,
            x = 6,
            y = 2,
            effectType = "diamondRoll",
            effectValue = 1,
            requires = "goldenRoll"
        },
        {
            id = "mythicRoll",
            baseId = "mythicRoll",
            level = 1,
            name = "Mythic Roll",
            desc = "Every 1,000 rolls grants +500x Luck!",
            cost = 1000000000,
            x = 7,
            y = 1,
            effectType = "mythicRoll",
            effectValue = 1,
            requires = "diamondRoll"
        },
        {
            id = "cosmicRoll",
            baseId = "cosmicRoll",
            level = 1,
            name = "Cosmic Roll",
            desc = "Every 10,000 rolls grants +5,000x Luck!",
            cost = 1000000000000,
            x = 8,
            y = 0,
            effectType = "cosmicRoll",
            effectValue = 1,
            requires = "mythicRoll"
        },
        {
            id = "earnings1",
            baseId = "earnings",
            level = 1,
            name = "Money 1",
            desc = "+10% Earnings Multiplier",
            cost = 100,
            x = 0,
            y = 1,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "start"
        },
        {
            id = "earnings2",
            baseId = "earnings",
            level = 2,
            name = "Money 2",
            desc = "+10% Earnings Multiplier",
            cost = 500,
            x = 0,
            y = 2,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings1"
        },
        {
            id = "earnings3",
            baseId = "earnings",
            level = 3,
            name = "Money 3",
            desc = "+10% Earnings Multiplier",
            cost = 3000,
            x = 0,
            y = 3,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings2"
        },
        {
            id = "earnings4",
            baseId = "earnings",
            level = 4,
            name = "Money 4",
            desc = "+10% Earnings Multiplier",
            cost = 20000,
            x = 0,
            y = 4,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings3"
        },
        {
            id = "earnings5",
            baseId = "earnings",
            level = 5,
            name = "Money 5",
            desc = "+10% Earnings Multiplier",
            cost = 150000,
            x = 0,
            y = 5,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings4"
        },
        {
            id = "earnings6",
            baseId = "earnings",
            level = 6,
            name = "Money 6",
            desc = "+10% Earnings Multiplier",
            cost = 1000000,
            x = 0,
            y = 6,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings5"
        },
        {
            id = "earnings7",
            baseId = "earnings",
            level = 7,
            name = "Money 7",
            desc = "+10% Earnings Multiplier",
            cost = 6000000,
            x = 0,
            y = 7,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings6"
        },
        {
            id = "earnings8",
            baseId = "earnings",
            level = 8,
            name = "Money 8",
            desc = "+10% Earnings Multiplier",
            cost = 35000000,
            x = 0,
            y = 8,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings7"
        },
        {
            id = "earnings9",
            baseId = "earnings",
            level = 9,
            name = "Money 9",
            desc = "+10% Earnings Multiplier",
            cost = 200000000,
            x = 0,
            y = 9,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings8"
        },
        {
            id = "earnings10",
            baseId = "earnings",
            level = 10,
            name = "Money 10",
            desc = "+10% Earnings Multiplier",
            cost = 1000000000,
            x = 0,
            y = 10,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings9"
        },
        {
            id = "earnings11",
            baseId = "earnings",
            level = 11,
            name = "Money 11",
            desc = "+10% Earnings Multiplier",
            cost = 5000000000,
            x = 0,
            y = 11,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings10"
        },
        {
            id = "earnings12",
            baseId = "earnings",
            level = 12,
            name = "Money 12",
            desc = "+10% Earnings Multiplier",
            cost = 25000000000,
            x = 0,
            y = 12,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings11"
        },
        {
            id = "earnings13",
            baseId = "earnings",
            level = 13,
            name = "Money 13",
            desc = "+10% Earnings Multiplier",
            cost = 125000000000,
            x = 0,
            y = 13,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings12"
        },
        {
            id = "earnings14",
            baseId = "earnings",
            level = 14,
            name = "Money 14",
            desc = "+10% Earnings Multiplier",
            cost = 600000000000,
            x = 0,
            y = 14,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings13"
        },
        {
            id = "earnings15",
            baseId = "earnings",
            level = 15,
            name = "Money 15",
            desc = "+10% Earnings Multiplier",
            cost = 2500000000000,
            x = 0,
            y = 15,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings14"
        },
        {
            id = "earnings16",
            baseId = "earnings",
            level = 16,
            name = "Money 16",
            desc = "+10% Earnings Multiplier",
            cost = 10000000000000,
            x = 0,
            y = 16,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings15"
        },
        {
            id = "earnings17",
            baseId = "earnings",
            level = 17,
            name = "Money 17",
            desc = "+10% Earnings Multiplier",
            cost = 40000000000000,
            x = 0,
            y = 17,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings16"
        },
        {
            id = "earnings18",
            baseId = "earnings",
            level = 18,
            name = "Money 18",
            desc = "+10% Earnings Multiplier",
            cost = 150000000000000,
            x = 0,
            y = 18,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings17"
        },
        {
            id = "earnings19",
            baseId = "earnings",
            level = 19,
            name = "Money 19",
            desc = "+10% Earnings Multiplier",
            cost = 500000000000000,
            x = 0,
            y = 19,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings18"
        },
        {
            id = "earnings20",
            baseId = "earnings",
            level = 20,
            name = "Money 20",
            desc = "+10% Earnings Multiplier",
            cost = 1500000000000000,
            x = 0,
            y = 20,
            effectType = "earnings",
            effectValue = 0.1,
            requires = "earnings19"
        },
        {
            id = "ultraincome1",
            baseId = "earnings",
            level = 21,
            name = "Ultra Income 1",
            desc = "+50% Earnings Multiplier",
            cost = 1.5e16,
            x = 0,
            y = 21,
            effectType = "ultraincome",
            effectValue = 1.5,
            requires = "earnings20"
        },
        {
            id = "ultraincome2",
            baseId = "earnings",
            level = 22,
            name = "Ultra Income 2",
            desc = "+50% Earnings Multiplier",
            cost = 1.5e17,
            x = 0,
            y = 22,
            effectType = "ultraincome",
            effectValue = 1.5,
            requires = "ultraincome1"
        },
        {
            id = "ultraincome3",
            baseId = "earnings",
            level = 23,
            name = "Ultra Income 3",
            desc = "+50% Earnings Multiplier",
            cost = 1.5e18,
            x = 0,
            y = 23,
            effectType = "ultraincome",
            effectValue = 1.5,
            requires = "ultraincome2"
        },
        {
            id = "ultraincome4",
            baseId = "earnings",
            level = 24,
            name = "Ultra Income 4",
            desc = "+50% Earnings Multiplier",
            cost = 1.5e19,
            x = 0,
            y = 24,
            effectType = "ultraincome",
            effectValue = 1.5,
            requires = "ultraincome3"
        },
        {
            id = "ultraincome5",
            baseId = "earnings",
            level = 25,
            name = "Ultra Income 5",
            desc = "+50% Earnings Multiplier",
            cost = 1.5e20,
            x = 0,
            y = 25,
            effectType = "ultraincome",
            effectValue = 1.5,
            requires = "ultraincome4"
        },
        {
            id = "ultraincome6",
            baseId = "earnings",
            level = 26,
            name = "Ultra Income 6",
            desc = "+50% Earnings Multiplier",
            cost = 1.5e21,
            x = 0,
            y = 26,
            effectType = "ultraincome",
            effectValue = 1.5,
            requires = "ultraincome5"
        },
        {
            id = "ultraincome7",
            baseId = "earnings",
            level = 27,
            name = "Ultra Income 7",
            desc = "+50% Earnings Multiplier",
            cost = 1.5e22,
            x = 0,
            y = 27,
            effectType = "ultraincome",
            effectValue = 1.5,
            requires = "ultraincome6"
        },
        {
            id = "ultraincome8",
            baseId = "earnings",
            level = 28,
            name = "Ultra Income 8",
            desc = "+50% Earnings Multiplier",
            cost = 1.5e23,
            x = 0,
            y = 28,
            effectType = "ultraincome",
            effectValue = 1.5,
            requires = "ultraincome7"
        },
        {
            id = "ultraincome9",
            baseId = "earnings",
            level = 29,
            name = "Ultra Income 9",
            desc = "+50% Earnings Multiplier",
            cost = 1.5e24,
            x = 0,
            y = 29,
            effectType = "ultraincome",
            effectValue = 1.5,
            requires = "ultraincome8"
        },
        {
            id = "ultraincome10",
            baseId = "earnings",
            level = 30,
            name = "Ultra Income 10",
            desc = "+50% Earnings Multiplier",
            cost = 1.5e25,
            x = 0,
            y = 30,
            effectType = "ultraincome",
            effectValue = 1.5,
            requires = "ultraincome9"
        },
        {
            id = "ultraincome11",
            baseId = "earnings",
            level = 31,
            name = "Ultra Income 11",
            desc = "+50% Earnings Multiplier",
            cost = 1.5e26,
            x = 0,
            y = 31,
            effectType = "ultraincome",
            effectValue = 1.5,
            requires = "ultraincome10"
        },
        {
            id = "ultraincome12",
            baseId = "earnings",
            level = 32,
            name = "Ultra Income 12",
            desc = "+50% Earnings Multiplier",
            cost = 1.5e27,
            x = 0,
            y = 32,
            effectType = "ultraincome",
            effectValue = 1.5,
            requires = "ultraincome11"
        },
        {
            id = "ultraincome13",
            baseId = "earnings",
            level = 33,
            name = "Ultra Income 13",
            desc = "+50% Earnings Multiplier",
            cost = 1.5e28,
            x = 0,
            y = 33,
            effectType = "ultraincome",
            effectValue = 1.5,
            requires = "ultraincome12"
        },
        {
            id = "ultraincome14",
            baseId = "earnings",
            level = 34,
            name = "Ultra Income 14",
            desc = "+50% Earnings Multiplier",
            cost = 1.5e29,
            x = 0,
            y = 34,
            effectType = "ultraincome",
            effectValue = 1.5,
            requires = "ultraincome13"
        },
        {
            id = "ultraincome15",
            baseId = "earnings",
            level = 35,
            name = "Ultra Income 15",
            desc = "+50% Earnings Multiplier",
            cost = 1.5e30,
            x = 0,
            y = 35,
            effectType = "ultraincome",
            effectValue = 1.5,
            requires = "ultraincome14"
        },
        {
            id = "slot2",
            baseId = "slot",
            level = 2,
            name = "Equip Slot 2",
            desc = "Unlock a second equip slot",
            cost = 1000000,
            x = -1,
            y = 1,
            effectType = "slot2",
            effectValue = 1,
            requires = "start"
        },
        {
            id = "slot3",
            baseId = "slot",
            level = 3,
            name = "Equip Slot 3",
            desc = "Unlock a third equip slot",
            cost = 1000000000,
            x = -2,
            y = 2,
            effectType = "slot3",
            effectValue = 1,
            requires = "slot2"
        },
        {
            id = "multiBall1",
            baseId = "multiBall",
            level = 1,
            name = "Multi-Ball 1",
            desc = "+0.5% Multi-Ball Chance",
            cost = 100,
            x = -1,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "start"
        },
        {
            id = "multiBall2",
            baseId = "multiBall",
            level = 2,
            name = "Multi-Ball 2",
            desc = "+0.5% Multi-Ball Chance",
            cost = 500,
            x = -2,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall1"
        },
        {
            id = "multiBall3",
            baseId = "multiBall",
            level = 3,
            name = "Multi-Ball 3",
            desc = "+0.5% Multi-Ball Chance",
            cost = 3000,
            x = -3,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall2"
        },
        {
            id = "multiBall4",
            baseId = "multiBall",
            level = 4,
            name = "Multi-Ball 4",
            desc = "+0.5% Multi-Ball Chance",
            cost = 20000,
            x = -4,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall3"
        },
        {
            id = "multiBall5",
            baseId = "multiBall",
            level = 5,
            name = "Multi-Ball 5",
            desc = "+0.5% Multi-Ball Chance",
            cost = 150000,
            x = -5,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall4"
        },
        {
            id = "multiBall6",
            baseId = "multiBall",
            level = 6,
            name = "Multi-Ball 6",
            desc = "+0.5% Multi-Ball Chance",
            cost = 1000000,
            x = -6,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall5"
        },
        {
            id = "multiBall7",
            baseId = "multiBall",
            level = 7,
            name = "Multi-Ball 7",
            desc = "+0.5% Multi-Ball Chance",
            cost = 6000000,
            x = -7,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall6"
        },
        {
            id = "multiBall8",
            baseId = "multiBall",
            level = 8,
            name = "Multi-Ball 8",
            desc = "+0.5% Multi-Ball Chance",
            cost = 35000000,
            x = -8,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall7"
        },
        {
            id = "multiBall9",
            baseId = "multiBall",
            level = 9,
            name = "Multi-Ball 9",
            desc = "+0.5% Multi-Ball Chance",
            cost = 200000000,
            x = -9,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall8"
        },
        {
            id = "multiBall10",
            baseId = "multiBall",
            level = 10,
            name = "Multi-Ball 10",
            desc = "+0.5% Multi-Ball Chance",
            cost = 1000000000,
            x = -10,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall9"
        },
        {
            id = "multiBall11",
            baseId = "multiBall",
            level = 11,
            name = "Multi-Ball 11",
            desc = "+0.5% Multi-Ball Chance",
            cost = 5000000000,
            x = -11,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall10"
        },
        {
            id = "multiBall12",
            baseId = "multiBall",
            level = 12,
            name = "Multi-Ball 12",
            desc = "+0.5% Multi-Ball Chance",
            cost = 25000000000,
            x = -12,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall11"
        },
        {
            id = "multiBall13",
            baseId = "multiBall",
            level = 13,
            name = "Multi-Ball 13",
            desc = "+0.5% Multi-Ball Chance",
            cost = 125000000000,
            x = -13,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall12"
        },
        {
            id = "multiBall14",
            baseId = "multiBall",
            level = 14,
            name = "Multi-Ball 14",
            desc = "+0.5% Multi-Ball Chance",
            cost = 600000000000,
            x = -14,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall13"
        },
        {
            id = "multiBall15",
            baseId = "multiBall",
            level = 15,
            name = "Multi-Ball 15",
            desc = "+0.5% Multi-Ball Chance",
            cost = 2500000000000,
            x = -15,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall14"
        },
        {
            id = "multiBall16",
            baseId = "multiBall",
            level = 16,
            name = "Multi-Ball 16",
            desc = "+0.5% Multi-Ball Chance",
            cost = 10000000000000,
            x = -16,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall15"
        },
        {
            id = "multiBall17",
            baseId = "multiBall",
            level = 17,
            name = "Multi-Ball 17",
            desc = "+0.5% Multi-Ball Chance",
            cost = 40000000000000,
            x = -17,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall16"
        },
        {
            id = "multiBall18",
            baseId = "multiBall",
            level = 18,
            name = "Multi-Ball 18",
            desc = "+0.5% Multi-Ball Chance",
            cost = 150000000000000,
            x = -18,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall17"
        },
        {
            id = "multiBall19",
            baseId = "multiBall",
            level = 19,
            name = "Multi-Ball 19",
            desc = "+0.5% Multi-Ball Chance",
            cost = 500000000000000,
            x = -19,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall18"
        },
        {
            id = "multiBall20",
            baseId = "multiBall",
            level = 20,
            name = "Multi-Ball 20",
            desc = "+0.5% Multi-Ball Chance",
            cost = 1500000000000000,
            x = -20,
            y = 0,
            effectType = "multiBall",
            effectValue = 0.005,
            requires = "multiBall19"
        },
        {
            id = "bouncyPegs1",
            baseId = "bouncyPegs",
            level = 1,
            name = "Bouncy Pegs 1",
            desc = "+10% Bounciness",
            cost = 1000,
            x = -1,
            y = -1,
            effectType = "bouncyPegs",
            effectValue = 0.1,
            requires = "start"
        },
        {
            id = "bouncyPegs2",
            baseId = "bouncyPegs",
            level = 2,
            name = "Bouncy Pegs 2",
            desc = "+10% Bounciness",
            cost = 10000,
            x = -2,
            y = -2,
            effectType = "bouncyPegs",
            effectValue = 0.1,
            requires = "bouncyPegs1"
        },
        {
            id = "bouncyPegs3",
            baseId = "bouncyPegs",
            level = 3,
            name = "Bouncy Pegs 3",
            desc = "+10% Bounciness",
            cost = 100000,
            x = -3,
            y = -3,
            effectType = "bouncyPegs",
            effectValue = 0.1,
            requires = "bouncyPegs2"
        },
        {
            id = "bouncyPegs4",
            baseId = "bouncyPegs",
            level = 4,
            name = "Bouncy Pegs 4",
            desc = "+10% Bounciness",
            cost = 1000000,
            x = -4,
            y = -4,
            effectType = "bouncyPegs",
            effectValue = 0.1,
            requires = "bouncyPegs3"
        },
        {
            id = "bouncyPegs5",
            baseId = "bouncyPegs",
            level = 5,
            name = "Bouncy Pegs 5",
            desc = "+10% Bounciness",
            cost = 10000000,
            x = -5,
            y = -5,
            effectType = "bouncyPegs",
            effectValue = 0.1,
            requires = "bouncyPegs4"
        },
        {
            id = "goldenPeg1",
            baseId = "goldenPeg",
            level = 1,
            name = "Golden Peg 1",
            desc = "Makes a peg golden. Golden pegs make balls give 2x money on collision.",
            cost = 100000,
            x = -3,
            y = -2,
            effectType = "goldenPeg",
            effectValue = 1,
            requires = "bouncyPegs2"
        },
        {
            id = "goldenPeg2",
            baseId = "goldenPeg",
            level = 2,
            name = "Golden Peg 2",
            desc = "Makes 2 pegs golden. Golden pegs make balls give 2x money on collision.",
            cost = 500000,
            x = -4,
            y = -2,
            effectType = "goldenPeg",
            effectValue = 2,
            requires = "goldenPeg1"
        },
        {
            id = "goldenPeg3",
            baseId = "goldenPeg",
            level = 3,
            name = "Golden Peg 3",
            desc = "Makes 3 pegs golden. Golden pegs make balls give 2x money on collision.",
            cost = 2500000,
            x = -5,
            y = -2,
            effectType = "goldenPeg",
            effectValue = 3,
            requires = "goldenPeg2"
        },
        {
            id = "diamondPeg1",
            baseId = "diamondPeg",
            level = 1,
            name = "Diamond Peg 1",
            desc = "Makes a golden peg diamond. Diamond pegs make balls give 5x money on collision.",
            cost = 10000000000,
            x = -6,
            y = -2,
            effectType = "diamondPeg",
            effectValue = 1,
            requires = "goldenPeg3"
        },
        {
            id = "diamondPeg2",
            baseId = "diamondPeg",
            level = 2,
            name = "Diamond Peg 2",
            desc = "Makes 2 golden pegs diamond. Diamond pegs make balls give 5x money on collision.",
            cost = 30000000000,
            x = -7,
            y = -2,
            effectType = "diamondPeg",
            effectValue = 2,
            requires = "diamondPeg1"
        },
        {
            id = "diamondPeg3",
            baseId = "diamondPeg",
            level = 3,
            name = "Diamond Peg 3",
            desc = "Makes 3 golden pegs diamond. Diamond pegs make balls give 5x money on collision.",
            cost = 100000000000,
            x = -8,
            y = -2,
            effectType = "diamondPeg",
            effectValue = 3,
            requires = "diamondPeg2"
        },
        {
            id = "cosmicPeg1",
            baseId = "cosmicPeg",
            level = 1,
            name = "Cosmic Peg 1",
            desc = "Makes a diamond peg cosmic. Cosmic pegs make balls give 15x money on collision.",
            cost = 10000000000000,
            x = -9,
            y = -2,
            effectType = "cosmicPeg",
            effectValue = 1,
            requires = "diamondPeg3"
        },
        {
            id = "cosmicPeg2",
            baseId = "cosmicPeg",
            level = 2,
            name = "Cosmic Peg 2",
            desc = "Makes 2 diamond pegs cosmic. Cosmic pegs make balls give 15x money on collision.",
            cost = 30000000000000,
            x = -10,
            y = -2,
            effectType = "cosmicPeg",
            effectValue = 2,
            requires = "cosmicPeg1"
        },
        {
            id = "cosmicPeg3",
            baseId = "cosmicPeg",
            level = 3,
            name = "Cosmic Peg 3",
            desc = "Makes 3 diamond pegs cosmic. Cosmic pegs make balls give 15x money on collision.",
            cost = 100000000000000,
            x = -11,
            y = -2,
            effectType = "cosmicPeg",
            effectValue = 3,
            requires = "cosmicPeg2"
        },
        {
            id = "teslaPeg1",
            baseId = "teslaPeg",
            level = 1,
            name = "Tesla Peg 1",
            desc = "Makes a peg a tesla. Tesla pegs shock nearby balls. If multiple tesla pegs exist at once, creates a lightning field between them.",
            cost = 1e16,
            x = -12,
            y = -2,
            effectType = "teslaPeg",
            effectValue = 1,
            requires = "cosmicPeg3"
        },
        {
            id = "teslaPeg2",
            baseId = "teslaPeg",
            level = 2,
            name = "Tesla Peg 2",
            desc = "Makes 2 pegs tesla. Tesla pegs shock nearby balls. If multiple tesla pegs exist at once, creates a lightning field between them.",
            cost = 3e16,
            x = -13,
            y = -2,
            effectType = "teslaPeg",
            effectValue = 2,
            requires = "teslaPeg1"
        },
        {
            id = "teslaPeg3",
            baseId = "teslaPeg",
            level = 3,
            name = "Tesla Peg 3",
            desc = "Makes 3 pegs tesla. Tesla pegs shock nearby balls. If multiple tesla pegs exist at once, creates a lightning field between them.",
            cost = 1e17,
            x = -14,
            y = -2,
            effectType = "teslaPeg",
            effectValue = 3,
            requires = "teslaPeg2"
        },
        {
            id = "multiDrop1",
            baseId = "multiDrop",
            level = 1,
            name = "Multi-Drop 1",
            desc = "+1% chance to drop an extra ball",
            cost = 1.5e16,
            x = 22,
            y = -22,
            effectType = "multiDrop",
            effectValue = 0.01,
            requires = "dropSpeed20"
        },
        {
            id = "multiDrop2",
            baseId = "multiDrop",
            level = 2,
            name = "Multi-Drop 2",
            desc = "+1% chance to drop an extra ball",
            cost = 1.5e17,
            x = 23,
            y = -23,
            effectType = "multiDrop",
            effectValue = 0.02,
            requires = "multiDrop1"
        },
        {
            id = "multiDrop3",
            baseId = "multiDrop",
            level = 3,
            name = "Multi-Drop 3",
            desc = "+1% chance to drop an extra ball",
            cost = 1.5e18,
            x = 24,
            y = -24,
            effectType = "multiDrop",
            effectValue = 0.03,
            requires = "multiDrop2"
        },
        {
            id = "multiDrop4",
            baseId = "multiDrop",
            level = 4,
            name = "Multi-Drop 4",
            desc = "+1% chance to drop an extra ball",
            cost = 1.5e19,
            x = 25,
            y = -25,
            effectType = "multiDrop",
            effectValue = 0.04,
            requires = "multiDrop3"
        },
        {
            id = "multiDrop5",
            baseId = "multiDrop",
            level = 5,
            name = "Multi-Drop 5",
            desc = "+1% chance to drop an extra ball",
            cost = 1.5e20,
            x = 26,
            y = -26,
            effectType = "multiDrop",
            effectValue = 0.05,
            requires = "multiDrop4"
        },
        {
            id = "multiDrop6",
            baseId = "multiDrop",
            level = 6,
            name = "Multi-Drop 6",
            desc = "+1% chance to drop an extra ball",
            cost = 1.5e21,
            x = 27,
            y = -27,
            effectType = "multiDrop",
            effectValue = 0.06,
            requires = "multiDrop5"
        },
        {
            id = "multiDrop7",
            baseId = "multiDrop",
            level = 7,
            name = "Multi-Drop 7",
            desc = "+1% chance to drop an extra ball",
            cost = 1.5e22,
            x = 28,
            y = -28,
            effectType = "multiDrop",
            effectValue = 0.07,
            requires = "multiDrop6"
        },
        {
            id = "multiDrop8",
            baseId = "multiDrop",
            level = 8,
            name = "Multi-Drop 8",
            desc = "+1% chance to drop an extra ball",
            cost = 1.5e23,
            x = 29,
            y = -29,
            effectType = "multiDrop",
            effectValue = 0.08,
            requires = "multiDrop7"
        },
        {
            id = "multiDrop9",
            baseId = "multiDrop",
            level = 9,
            name = "Multi-Drop 9",
            desc = "+1% chance to drop an extra ball",
            cost = 1.5e24,
            x = 30,
            y = -30,
            effectType = "multiDrop",
            effectValue = 0.09,
            requires = "multiDrop8"
        },
        {
            id = "multiDrop10",
            baseId = "multiDrop",
            level = 10,
            name = "Multi-Drop 10",
            desc = "+1% chance to drop an extra ball",
            cost = 1.5e25,
            x = 31,
            y = -31,
            effectType = "multiDrop",
            effectValue = 0.1,
            requires = "multiDrop9"
        },
        {
            id = "rollDiscount1",
            baseId = "rollDiscount",
            level = 1,
            name = "Roll Discount 1",
            desc = "5% less rolls needed for Golden/Diamond/Mythic/Cosmic Rolls",
            cost = 1.5e16,
            x = 22,
            y = 22,
            effectType = "rollDiscount",
            effectValue = 0.05,
            requires = "rollSpeed20"
        },
        {
            id = "rollDiscount2",
            baseId = "rollDiscount",
            level = 2,
            name = "Roll Discount 2",
            desc = "10% less rolls needed for Golden/Diamond/Mythic/Cosmic Rolls",
            cost = 1.5e17,
            x = 23,
            y = 23,
            effectType = "rollDiscount",
            effectValue = 0.1,
            requires = "rollDiscount1"
        },
        {
            id = "rollDiscount3",
            baseId = "rollDiscount",
            level = 3,
            name = "Roll Discount 3",
            desc = "15% less rolls needed for Golden/Diamond/Mythic/Cosmic Rolls",
            cost = 1.5e18,
            x = 24,
            y = 24,
            effectType = "rollDiscount",
            effectValue = 0.15,
            requires = "rollDiscount2"
        },
        {
            id = "rollDiscount4",
            baseId = "rollDiscount",
            level = 4,
            name = "Roll Discount 4",
            desc = "20% less rolls needed for Golden/Diamond/Mythic/Cosmic Rolls",
            cost = 1.5e19,
            x = 25,
            y = 25,
            effectType = "rollDiscount",
            effectValue = 0.2,
            requires = "rollDiscount3"
        },
        {
            id = "rollDiscount5",
            baseId = "rollDiscount",
            level = 5,
            name = "Roll Discount 5",
            desc = "25% less rolls needed for Golden/Diamond/Mythic/Cosmic Rolls",
            cost = 1.5e20,
            x = 26,
            y = 26,
            effectType = "rollDiscount",
            effectValue = 0.25,
            requires = "rollDiscount4"
        },
        {
            id = "rollDiscount6",
            baseId = "rollDiscount",
            level = 6,
            name = "Roll Discount 6",
            desc = "30% less rolls needed for Golden/Diamond/Mythic/Cosmic Rolls",
            cost = 1.5e21,
            x = 27,
            y = 27,
            effectType = "rollDiscount",
            effectValue = 0.3,
            requires = "rollDiscount5"
        },
        {
            id = "rollDiscount7",
            baseId = "rollDiscount",
            level = 7,
            name = "Roll Discount 7",
            desc = "35% less rolls needed for Golden/Diamond/Mythic/Cosmic Rolls",
            cost = 1.5e22,
            x = 28,
            y = 28,
            effectType = "rollDiscount",
            effectValue = 0.35,
            requires = "rollDiscount6"
        },
        {
            id = "rollDiscount8",
            baseId = "rollDiscount",
            level = 8,
            name = "Roll Discount 8",
            desc = "40% less rolls needed for Golden/Diamond/Mythic/Cosmic Rolls",
            cost = 1.5e23,
            x = 29,
            y = 29,
            effectType = "rollDiscount",
            effectValue = 0.4,
            requires = "rollDiscount7"
        },
        {
            id = "rollDiscount9",
            baseId = "rollDiscount",
            level = 9,
            name = "Roll Discount 9",
            desc = "45% less rolls needed for Golden/Diamond/Mythic/Cosmic Rolls",
            cost = 1.5e24,
            x = 30,
            y = 30,
            effectType = "rollDiscount",
            effectValue = 0.45,
            requires = "rollDiscount8"
        },
        {
            id = "rollDiscount10",
            baseId = "rollDiscount",
            level = 10,
            name = "Roll Discount 10",
            desc = "50% less rolls needed for Golden/Diamond/Mythic/Cosmic Rolls",
            cost = 1.5e25,
            x = 31,
            y = 31,
            effectType = "rollDiscount",
            effectValue = 0.5,
            requires = "rollDiscount9"
        },
        {
            id = "blastRadius1",
            baseId = "blastRadius",
            level = 1,
            name = "Explosion Radius 1",
            desc = "+0.5 Explosion Radius",
            cost = 500,
            x = -2,
            y = 4,
            effectType = "blastRadius",
            effectValue = 10.5,
            requires = "shooter"
        },
        {
            id = "blastRadius2",
            baseId = "blastRadius",
            level = 2,
            name = "Explosion Radius 2",
            desc = "+0.5 Explosion Radius",
            cost = 20000,
            x = -3,
            y = 5,
            effectType = "blastRadius",
            effectValue = 11,
            requires = "blastRadius1"
        },
        {
            id = "blastRadius3",
            baseId = "blastRadius",
            level = 3,
            name = "Explosion Radius 3",
            desc = "+0.5 Explosion Radius",
            cost = 1000000,
            x = -4,
            y = 6,
            effectType = "blastRadius",
            effectValue = 11.5,
            requires = "blastRadius2"
        },
        {
            id = "blastRadius4",
            baseId = "blastRadius",
            level = 4,
            name = "Explosion Radius 4",
            desc = "+0.5 Explosion Radius",
            cost = 35000000,
            x = -5,
            y = 7,
            effectType = "blastRadius",
            effectValue = 12,
            requires = "blastRadius3"
        },
        {
            id = "blastRadius5",
            baseId = "blastRadius",
            level = 5,
            name = "Explosion Radius 5",
            desc = "+0.5 Explosion Radius",
            cost = 1000000000,
            x = -6,
            y = 8,
            effectType = "blastRadius",
            effectValue = 12.5,
            requires = "blastRadius4"
        },
        {
            id = "blastRadius6",
            baseId = "blastRadius",
            level = 6,
            name = "Explosion Radius 6",
            desc = "+0.5 Explosion Radius",
            cost = 25000000000,
            x = -7,
            y = 9,
            effectType = "blastRadius",
            effectValue = 13,
            requires = "blastRadius5"
        },
        {
            id = "blastRadius7",
            baseId = "blastRadius",
            level = 7,
            name = "Explosion Radius 7",
            desc = "+0.5 Explosion Radius",
            cost = 600000000000,
            x = -8,
            y = 10,
            effectType = "blastRadius",
            effectValue = 13.5,
            requires = "blastRadius6"
        },
        {
            id = "blastRadius8",
            baseId = "blastRadius",
            level = 8,
            name = "Explosion Radius 8",
            desc = "+0.5 Explosion Radius",
            cost = 10000000000000,
            x = -9,
            y = 11,
            effectType = "blastRadius",
            effectValue = 14,
            requires = "blastRadius7"
        },
        {
            id = "blastRadius9",
            baseId = "blastRadius",
            level = 9,
            name = "Explosion Radius 9",
            desc = "+0.5 Explosion Radius",
            cost = 150000000000000,
            x = -10,
            y = 12,
            effectType = "blastRadius",
            effectValue = 14.5,
            requires = "blastRadius8"
        },
        {
            id = "blastRadius10",
            baseId = "blastRadius",
            level = 10,
            name = "Explosion Radius 10",
            desc = "+0.5 Explosion Radius",
            cost = 1500000000000000,
            x = -11,
            y = 13,
            effectType = "blastRadius",
            effectValue = 15,
            requires = "blastRadius9"
        }
    },
    ById = {}
}

for i, v in ipairs(t.Upgrades) do
    t.ById[v.id] = v
end

function t.GetChildren(p1) --[[ GetChildren | Line: 240 | Upvalues: t (copy) ]]
    local t2 = {}

    for i, v in ipairs(t.Upgrades) do
        if v.requires == p1 then
            table.insert(t2, v)
        end
    end

    return t2
end
function t.CanPurchase(p1, p2) --[[ CanPurchase | Line: 245 | Upvalues: t (copy) ]]
    local v1 = t.ById[p1]

    if not v1 then
        return false
    end

    if p2[p1] then
        return false
    end

    if v1.requires == nil then
        return true
    end

    return p2[v1.requires] == true
end

return t
